on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n zsimovanlockertest -g zsimovanlockertestb034-rg --location "East US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n zsimovanlockertest --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n zsimovanlockertest --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n zsimovanlockertest --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: zsimovanlockertest.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/src/Admin" -f  "src/Admin/Dockerfile" -t zsimovanlockertest.azurecr.io/zsimovanlocker:${{ github.sha }}
        docker push zsimovanlockertest.azurecr.io/zsimovanlocker:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_zsimovanlocker_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep zsimovanlockere087 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace zsimovanlockere087`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: zsimovanlockere087
        container-registry-url: zsimovanlockertest.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: zsimovanlockdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: zsimovanlockere087
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          zsimovanlockertest.azurecr.io/zsimovanlocker:${{ github.sha }}
        imagepullsecrets: |
          zsimovanlockdockerauth